
basic:
  types_of_cofee:
    capucinno:
      time: 24h
      limit: 2
    americano:
      time: 30m
      limit: 3
advance:
  types_of_cofee:
    capucinno:
      time: 24h
      limit: 2
    americano:
      time: 30m
      limit: 3
