basic:
  cofee_types:
      - name: capucinno
        time: 24h
        limit: 1
      - name: espresso
        time: 24h
        limit: 2
      - name: americano
        time: 24h
        limit: 3
cofeelover:
  cofee_types:
    - name: capucinno
      time: 24h
      limit: 5
    - name: espresso
      time: 24h
      limit: 5
    - name: americano
      time: 24h
      limit: 5
americano_maniac:
  cofee_types:
      - name: capucinno
        time: 24h
        limit: 1
      - name: espresso
        time: 24h
        limit: 2
      - name: americano
        time: 1h
        limit: 5
